var express = require('express');
var connection = require('../model/mysqlConnection');

var router = express.Router();

/* GET users listing. */
router.get('/', function(req, res, next) {
	console.log("【INFO】detail start");

	var query = 'SELECT EMPLOYEE_NO FROM MST_EMPLOYEE_BASE';

	/**
	詳細SQL_情報処理国家資格の一覧を取得する用
	select
	NATIONAL.QUALIFY_NAME,
	NATIONAL_HISTORY.ACQUIRE_DATE
	from
	MST_NATIONAL_QUALIFY NATIONAL
	LEFT OUTER JOIN TRN_NATIONAL_QUALIFY_HISTORY NATIONAL_HISTORY
	on NATIONAL.QUALIFICATION_CD = NATIONAL_HISTORY.QUALIFICATION_CD
	where
	NATIONAL_HISTORY.EMPLOYEE_NO = 'XXXX'
	order by NATIONAL.ORDER asc
	*/

	/**
	詳細SQL_その他資格を取得した一覧用
	select
	QUALIFY_NAME,
	ACQUIRE_DATE
	from
	TRN_SUB_QUALIFY_HISTORY
	where
	EMPLOYEE_NO = 'XXXX'
	order by SEQ_NO asc
	*/

	/**
	詳細SQL_社員情報を表示する用
	select
	COMPANY.COMPANY_NAME,
	BASE.EMPLOYEE_TYPE,
	lpad(BASE.EMPLOYEE_NO, 5, '0') as EMPLOYEE_NO,
	BASE.EMPLOYEE_FAMILY_NAME,
	BASE.EMPLOYEE_FIRST_NAME,
	BASE.EMPLOYEE_FAMILY_NAME_KANA,
	BASE.EMPLOYEE_FIRST_NAME_KANA
	DEPT.GROUP_NAME,
	DEPT.DEPT_NAME,
	DEPT.SECTION_NAME,
	POSITION.POSITION,
	POSITION.UPGRADE_DATE,
	CLIENT.CLIENT_NAME,
	PLACE.WORK_PLACE_NAME,
	BASE.EMAIL,
	BASE.EMPLOY_DATE,
	PERSONAL.GENDER,
	PERSONAL.BIRTH_DATE,
	PERSONAL.ZIP,
	PERSONAL.ADDRESS,
	PERSONAL.TEL_NO,
	PERSONAL.CELL_TEL_NO,
	PERSONAL.WORKING_TEL_NO,
	PERSONAL.ZIP_HOME,
	PERSONAL.ADDRESS_HOME,
	PERSONAL.TEL_NO_HOME,
	EDUCATION.EDUCATION,
	EDUCATION.SCHOOL,
	EDUCATION.COURSE
	from
	MST_EMPLOYEE_BASE BASE
	INNER JOIN MST_COMPANY COMPANY
	on BASE.COMPANY_CD = COMPANY.COMPANY_CD
	INNER JOIN MST_DEPT DEPT
	on BASE.DEPT_CD = DEPT.DEPT_CD
	LEFT OUTER JOIN TRN_POSITION_UPGRADE POSITION
	on BASE.EMPLOYEE_NO = POSITION.EMPLOYEE_NO
	order by POSITION.UPGRADE_DATE desc
	limit 1
	INNER JOIN MST_CLIENT CLIENT
	on BASE.CLIENT_CD = CLIENT.CLIENT_CD
	INNER JOIN MST_WORK_PLACE PLACE
	on BASE.CLIENT_CD = PLACE.CLIENT_CD
	and BASE.WORK_PLACE_CD = PLACE.WORK_PLACE_CD
	INNER JOIN MST_EMPLOYEE_PERSONAL PERSONAL
	on BASE.EMPLOYEE_NO = PERSONAL.EMPLOYEE_NO
	INNER JOIN TRN_EDUCATION_BACKGROUND EDUCATION
	on BASE.EMPLOYEE_NO = EDUCATION.EMPLOYEE_NO
	where
	BASE.EMPLOYEE_NO = 'XXXXX'
	*/

	connection.query(query, function(err, rows) {
		console.dir(rows[0].EMPLOYEE_NO);
		res.render('detail',
		{
			title: '詳細画面',
			testItem: rows[0].EMPLOYEE_NO
		});
	});
});

module.exports = router;
